version: '3.8'

services:

  consul:
    image: consul:1.15.4
    ports:
      - "8500:8500"
    volumes:
      - consul_data:/consul/data
    command: "agent -dev -client 0.0.0.0"

volumes:
  consul_data:


